name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        description: 'Version of new release (ex. 1.2.3)'
        required: false
        type: string
    outputs:
      artifact-id:
        description: 'ID of uploaded artifact'
        value: ${{ jobs.build.outputs.artifact-id }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'

      - name: Download dependencies
        run: make deps

      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1

      - name: Run tests
        run: make test

      - name: Determine version
        id: version
        run: |
          VERSION="${{ inputs.version }}"
          if [ -z "$VERSION" ]; then
            VERSION=$(git describe --tags --dirty --always | sed 's/^v//')
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build binaries
        env:
          VERSION: ${{ steps.version.outputs.version }}
          GIT_COMMIT: ${{ github.sha }}
        run: make build-all

      - name: Upload SBOM to bifrost
        if: ${{ github.repository_owner == 'bifrostsec' }}
        uses: bifrostsec/submit-sbom-action@75022880ab1d80abd985c6b5b2c745e5d1d67e88 # v1.1.1
        with:
          api-token: ${{ secrets.BIFROST_API_KEY }}
          service: 'bifrost-cli'
          service-version: ${{ steps.version.outputs.version }}
          dependency-graph: true

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: bifrost-binaries
          path: build/bifrost-*
