name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        description: 'Version of new release (ex. 1.2.3)'
        required: false
        type: string
    outputs:
      artifact-id:
        description: 'ID of uploaded artifact'
        value: ${{ jobs.upload-artifact.outputs.artifact-id }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Download dependencies
        run: make deps

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9

      - name: Run tests
        run: make test

      - name: Determine version
        id: version
        run: |
          VERSION="${{ inputs.version }}"
          if [ -z "$VERSION" ]; then
            VERSION=$(git describe --tags --always | sed 's/^v//')
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: make GIT_COMMIT=${{ github.sha }} VERSION=${{ steps.version.outputs.version }} build-all

      - name: Generate SBOM
        uses: CycloneDX/gh-gomod-generate-sbom@v2
        with:
          version: v1
          args: app -json -main cmd/bifrost -output sbom.cdx.json

      - name: Upload SBOM to bifrost
        if: ${{ github.repository_owner == 'bifrostsec' }}
        uses: bifrostsec/submit-sbom-action@v1
        with:
          api-token: ${{ secrets.BIFROST_API_KEY }}
          service: 'bifrost-cli'
          service-version: ${{ steps.version.outputs.version }}
          sbom-path: 'sbom.cdx.json'

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: bifrost-binaries
          path: build/bifrost-*
